alias \
    sudo='sudo ' \
    vim='nvim' \
    view='nvim -R' \
    szrc='. ~/.zshrc' \
    zrc='nvim $HOME/.zshrc' \
    vrc='nvim $XDG_CONFIG_HOME/nvim/init.vim' \
    alc='nvim $XDG_CONFIG_HOME/alacritty/alacritty.yml' \
    pbc='nvim $XDG_CONFIG_HOME/polybar/config' \
    rfc='nvim $XDG_CONFIG_HOME/rofi/config.rasi' \
    sxc='nvim $XDG_CONFIG_HOME/sxhkd/sxhkdrc' \
    bsc='nvim $XDG_CONFIG_HOME/bspwm/bspwmrc' \
    txc='nvim $XDG_CONFIG_HOME/tmux/tmux.conf' \
    tmux='tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf' \
    t='tmux' \
    tls='tmux ls' \
    tn='tmux new' \
    tns='tmux new -s' \
    ta='tmux a' \
    tat='tmux a -t' \
    dotfiles='cd $DOTFILES' \
    fonts='cd $FONTS' \
    screenshots='cd $SCREENSHOTS' \
    elr='cd $HOME/github/eulerv2' \
    mnm='cd $HOME/github/manim' \
    gcloud='docker run --rm --volumes-from gcloud-config gcr.io/google.com/cloudsdktool/cloud-sdk gcloud' \
    bq='docker run --rm --volumes-from gcloud-config gcr.io/google.com/cloudsdktool/cloud-sdk bq' \
    gsutil='docker run --rm --volumes-from gcloud-config gcr.io/google.com/cloudsdktool/cloud-sdk gsutil'
