alias \
    sudo='sudo ' \
    vim='nvim' \
    view='nvim -R' \
    szrc='. $HOME/.zshrc' \
    zrc='nvim $HOME/.zshrc' \
    brc='nvim $HOME/.bashrc' \
    vrc='nvim $HOME/.config/nvim/init.vim' \
    alc='nvim $HOME/.config/alacritty/alacritty.yml' \
    pbc='nvim $HOME/.config/polybar/config' \
    rfc='nvim $HOME/.config/rofi/config.rasi' \
    sxc='nvim $HOME/.config/sxhkd/sxhkdrc' \
    bsc='nvim $HOME/.config/bspwm/bspwmrc' \
    txc='nvim $HOME/.config/tmux/tmux.conf' \
    als='nvim $HOME/.config/zsh/custom/aliases.zsh' \
    stc='nvim $HOME/.config/st/config.h' \
    tmux='tmux -f $HOME/.config/tmux/tmux.conf' \
    t='tmux' \
    tls='tmux ls' \
    tn='tmux new' \
    tns='tmux new -s' \
    ta='tmux a' \
    tat='tmux a -t' \
    dotfiles='cd $DOTFILES' \
    fonts='cd $FONTS' \
    screenshots='cd $SCREENSHOTS' \
    elr='cd $HOME/github/eulertour' \
    mnm='cd $HOME/github/manim && workon manim'
