#! /bin/sh

polybar -r default &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding         $(xgetres polybar.height)
bspc config border_width        4
bspc config window_gap          48

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
